// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.edu.ufpb.receitas.domain;

import br.edu.ufpb.receitas.domain.IngredienteIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect IngredienteIntegrationTest_Roo_Configurable {
    
    declare @type: IngredienteIntegrationTest: @Configurable;
    
}
