// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.edu.ufpb.receitas.domain;

import br.edu.ufpb.receitas.domain.IngredienteDataOnDemand;
import br.edu.ufpb.receitas.domain.IngredienteIntegrationTest;
import br.edu.ufpb.receitas.repository.IngredienteDAO;
import br.edu.ufpb.receitas.service.IngredienteService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect IngredienteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: IngredienteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: IngredienteIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: IngredienteIntegrationTest: @Transactional;
    
    @Autowired
    IngredienteDataOnDemand IngredienteIntegrationTest.dod;
    
    @Autowired
    IngredienteService IngredienteIntegrationTest.ingredienteService;
    
    @Autowired
    IngredienteDAO IngredienteIntegrationTest.ingredienteDAO;
    
    @Test
    public void IngredienteIntegrationTest.testCountAllIngredientes() {
        Assert.assertNotNull("Data on demand for 'Ingrediente' failed to initialize correctly", dod.getRandomIngrediente());
        long count = ingredienteService.countAllIngredientes();
        Assert.assertTrue("Counter for 'Ingrediente' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void IngredienteIntegrationTest.testFindIngrediente() {
        Ingrediente obj = dod.getRandomIngrediente();
        Assert.assertNotNull("Data on demand for 'Ingrediente' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ingrediente' failed to provide an identifier", id);
        obj = ingredienteService.findIngrediente(id);
        Assert.assertNotNull("Find method for 'Ingrediente' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Ingrediente' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void IngredienteIntegrationTest.testFindAllIngredientes() {
        Assert.assertNotNull("Data on demand for 'Ingrediente' failed to initialize correctly", dod.getRandomIngrediente());
        long count = ingredienteService.countAllIngredientes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Ingrediente', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Ingrediente> result = ingredienteService.findAllIngredientes();
        Assert.assertNotNull("Find all method for 'Ingrediente' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Ingrediente' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void IngredienteIntegrationTest.testFindIngredienteEntries() {
        Assert.assertNotNull("Data on demand for 'Ingrediente' failed to initialize correctly", dod.getRandomIngrediente());
        long count = ingredienteService.countAllIngredientes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Ingrediente> result = ingredienteService.findIngredienteEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Ingrediente' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Ingrediente' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void IngredienteIntegrationTest.testFlush() {
        Ingrediente obj = dod.getRandomIngrediente();
        Assert.assertNotNull("Data on demand for 'Ingrediente' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ingrediente' failed to provide an identifier", id);
        obj = ingredienteService.findIngrediente(id);
        Assert.assertNotNull("Find method for 'Ingrediente' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyIngrediente(obj);
        Integer currentVersion = obj.getVersion();
        ingredienteDAO.flush();
        Assert.assertTrue("Version for 'Ingrediente' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IngredienteIntegrationTest.testUpdateIngredienteUpdate() {
        Ingrediente obj = dod.getRandomIngrediente();
        Assert.assertNotNull("Data on demand for 'Ingrediente' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ingrediente' failed to provide an identifier", id);
        obj = ingredienteService.findIngrediente(id);
        boolean modified =  dod.modifyIngrediente(obj);
        Integer currentVersion = obj.getVersion();
        Ingrediente merged = ingredienteService.updateIngrediente(obj);
        ingredienteDAO.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Ingrediente' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IngredienteIntegrationTest.testSaveIngrediente() {
        Assert.assertNotNull("Data on demand for 'Ingrediente' failed to initialize correctly", dod.getRandomIngrediente());
        Ingrediente obj = dod.getNewTransientIngrediente(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Ingrediente' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Ingrediente' identifier to be null", obj.getId());
        ingredienteService.saveIngrediente(obj);
        ingredienteDAO.flush();
        Assert.assertNotNull("Expected 'Ingrediente' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void IngredienteIntegrationTest.testDeleteIngrediente() {
        Ingrediente obj = dod.getRandomIngrediente();
        Assert.assertNotNull("Data on demand for 'Ingrediente' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ingrediente' failed to provide an identifier", id);
        obj = ingredienteService.findIngrediente(id);
        ingredienteService.deleteIngrediente(obj);
        ingredienteDAO.flush();
        Assert.assertNull("Failed to remove 'Ingrediente' with identifier '" + id + "'", ingredienteService.findIngrediente(id));
    }
    
}
