// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.edu.ufpb.receitas.domain;

import br.edu.ufpb.receitas.domain.ReceitaDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ReceitaDataOnDemand_Roo_Configurable {
    
    declare @type: ReceitaDataOnDemand: @Configurable;
    
}
