// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.edu.ufpb.receitas.domain;

import br.edu.ufpb.receitas.domain.Receita;
import br.edu.ufpb.receitas.domain.ReceitaDataOnDemand;
import br.edu.ufpb.receitas.repository.ReceitaDAO;
import br.edu.ufpb.receitas.service.ReceitaService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ReceitaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReceitaDataOnDemand: @Component;
    
    private Random ReceitaDataOnDemand.rnd = new SecureRandom();
    
    private List<Receita> ReceitaDataOnDemand.data;
    
    @Autowired
    ReceitaService ReceitaDataOnDemand.receitaService;
    
    @Autowired
    ReceitaDAO ReceitaDataOnDemand.receitaDAO;
    
    public Receita ReceitaDataOnDemand.getNewTransientReceita(int index) {
        Receita obj = new Receita();
        setDescricao(obj, index);
        setNome(obj, index);
        setPreparo(obj, index);
        return obj;
    }
    
    public void ReceitaDataOnDemand.setDescricao(Receita obj, int index) {
        String descricao = "descricao_" + index;
        obj.setDescricao(descricao);
    }
    
    public void ReceitaDataOnDemand.setNome(Receita obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public void ReceitaDataOnDemand.setPreparo(Receita obj, int index) {
        String preparo = "preparo_" + index;
        obj.setPreparo(preparo);
    }
    
    public Receita ReceitaDataOnDemand.getSpecificReceita(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Receita obj = data.get(index);
        Long id = obj.getId();
        return receitaService.findReceita(id);
    }
    
    public Receita ReceitaDataOnDemand.getRandomReceita() {
        init();
        Receita obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return receitaService.findReceita(id);
    }
    
    public boolean ReceitaDataOnDemand.modifyReceita(Receita obj) {
        return false;
    }
    
    public void ReceitaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = receitaService.findReceitaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Receita' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Receita>();
        for (int i = 0; i < 10; i++) {
            Receita obj = getNewTransientReceita(i);
            try {
                receitaService.saveReceita(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            receitaDAO.flush();
            data.add(obj);
        }
    }
    
}
